config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'

  resources :artists
  resources :lps

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
	has_many :lps, dependent: :destroy
	has_attached_file :image
	validates_attachment_file_name :image, :matches => [/png\Z/, /jpeg\Z/, /gif\Z/, /jpg\Z/]
	validates :name, presence: true
	validates :name, uniqueness: true
end

app/models/lp.rb
class Lp < ApplicationRecord
 	belongs_to :artist
  	has_attached_file :image
	validates_attachment_file_name :image, :matches => [/png\Z/, /jpeg\Z/, /gif\Z/, /jpg\Z/]
	validates :name, presence: true
	validates :artist_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
	def index
    @artists = Artist.all
  end

	def show
		@artist = Artist.find(params[:id])
	end

	def new
		@artist = Artist.new
  end

  def edit
		@artist = Artist.find(params[:id])
	end

  def create
  	@artist = Artist.new(artist_params)

  	if @artist.save
		  redirect_to @artist
		else
			render 'new'
		end
  end

	def update
		@artist = Artist.find(params[:id])
	 
  	if @artist.update(artist_params)
    	redirect_to @artist
  	else
    	render 'edit'
  	end
	end

	def destroy
	  @artist = Artist.find(params[:id])
	  @artist.destroy
	 
	  redirect_to @artist
	end

	private
	def artist_params
  	params.require(:artist).permit(:name, :description, :image)
	end
end

app/controllers/lps_controller.rb
class LpsController < ApplicationController
	def index
    @lps = Lp.all
  end

	def show
		@lp = Lp.find(params[:id])
	end

	def new
		@lp = Lp.new
  end

  def edit
		@lp = Lp.find(params[:id])
	end

	def create
		@lp = Lp.new(lp_params)

		if @lp.save
  		redirect_to @lp
  	else
  		render 'new'
  	end
	end

	def update
		@lp = Lp.find(params[:id])
	 
	  	if @lp.update(lp_params)
	    	redirect_to @lp
	  	else
	    	render 'edit'
	  	end
	end

	def destroy
	  @lp = Lp.find(params[:id])
	  @lp.destroy
	 
	  redirect_to @lp
	end

	private
	def lp_params
  	params.require(:lp).permit(:artist_id, :name, :description, :image)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/lps_helper.rb
module LpsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/artists/edit.html.erb
<section class="menu">
  <a href="javascript:history.back()" class="button">Back</a>
  <%= link_to 'Artists', artists_path, :class => "button active"  %>
  <%= link_to 'Albums', lps_path, :class => "button" %>
</section>

<div class="center_content">
  <h1>Edit artist</h1>

  <%= form_with(model: @artist, local: true) do |form| %>

    <% if @artist.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@artist.errors.count, "error") %> prohibited
          this artist from being saved:
        </h2>
        <ul>
          <% @artist.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="content_image">
      <% if @artist.image.exists? %>
        <%= image_tag @artist.image.url %></br>
      <% end %>
      <%= form.file_field :image %>
    </div>
   
    <div class="content_text">
      <p>
        <%= form.label :Name %><br>
        <%= form.text_field :name %>
      </p>

      <p>
        <%= form.label :Description %><br>
        <%= form.text_area :description %>
      </p>
    </div>

    <div class="clear"></div>
    <%= form.submit 'Update', :class => "button_update" %>

  <% end %>
</div>

app/views/artists/index.html.erb
<section class="menu">
  <%= link_to 'Artists', artists_path, :class => "button active"  %>
  <%= link_to 'Albums', lps_path, :class => "button" %>
</section>

<div class="center_content">
  <h1>Artists
  <%= link_to '<i class="fa fa-plus-circle"></i>'.html_safe, new_artist_path, :class => "button_new" %></h1>
   
  <table class="list">
   
    <% @artists.each do |artist| %>
      <tr>
        <td><div class="image" style="background-image: url(<%= artist.image.url %>)"></div></td>
        <td><%= artist.name %></td>
        <td><%= artist.description %></td>
        <td>
          <%= link_to '<i class="fa fa-eye"></i>'.html_safe, artist_path(artist) %>
        </td>
        <td>
          <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_artist_path(artist) %>
        </td>
        <td><%= link_to '<i class="fa fa-trash"></i>'.html_safe, artist_path(artist),
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>

  </table>
</div>

app/views/artists/new.html.erb
<section class="menu">
  <a href="javascript:history.back()" class="button">Back</a>
  <%= link_to 'Artists', artists_path, :class => "button active"  %>
  <%= link_to 'Albums', lps_path, :class => "button" %>
</section>

<div class="center_content">
	<h1>New Artist</h1>

	<%= form_for(:artist, :url => artists_path, :html => {:multipart => true}) do |form| %>

		<% if @artist.errors.any? %>
		    <div id="error_explanation">
		      	<h2>
			        <%= pluralize(@artist.errors.count, "error") %> prohibited
			        this artist from being saved:
		      	</h2>
		      	<ul>
			        <% @artist.errors.full_messages.each do |msg| %>
			          <li><%= msg %></li>
			        <% end %>
		      	</ul>
		    </div>
		<% end %>

	  	<p>
		    <%= form.label :Name %><br>
		    <%= form.text_field :name %>
	  	</p>
	 
	  	<p>
		    <%= form.label :Description %><br>
		    <%= form.text_area :description %>
	  	</p>

	  	<p>
		    <%= form.file_field :image %>
	  	</p>
	 
	  	<p>
	    	<%= form.submit 'Save' %>
	  	</p>
	<% end %>
</div>

app/views/artists/show.html.erb
<section class="menu">
  <a href="javascript:history.back()" class="button">Back</a>
  <%= link_to 'Artists', artists_path, :class => "button active"  %>
  <%= link_to 'Albums', lps_path, :class => "button" %>
</section>


  <%= link_to 'Edit', edit_artist_path(@artist) %>

<div class="center_content">
  <div class="content_image">
    <%= image_tag @artist.image.url %>
  </div>

  <div class="content_text">
    <p>
      <strong>Name:</strong>
      <%= @artist.name %>
    </p>
     
    <p>
      <strong>Description:</strong>
      <%= @artist.description %>
    </p>

    <p>
      <strong>Number of Albums:</strong>
      <%= @artist.lps.size %>
    </p>
  </div>

  <div class="clear"></div>
  <hr>

  <table class="list">
      <% @artist.lps.each do |lp| %>
        <tr>
          <td><div class="image" style="background-image: url(<%= lp.image.url %>)"></div></td>
          <td><%= lp.name %></td>
          <td><%= lp.description %></td>
          <td>
            <%= link_to '<i class="fa fa-eye"></i>'.html_safe, lp_path(lp) %>
          </td>
          <td>
            <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_lp_path(lp) %>
          </td>
          <td><%= link_to '<i class="fa fa-trash"></i>'.html_safe, lp_path(lp),
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
    <% end %>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lps/edit.html.erb
<section class="menu">
  <a href="javascript:history.back()" class="button">Back</a>
  <%= link_to 'Artists', artists_path, :class => "button"  %>
  <%= link_to 'Albums', lps_path, :class => "button active" %>
</section>

<div class="center_content">
  <h1>Edit Album</h1>

  <%= form_with(model: @lp, local: true) do |form| %>

    <% if @lp.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@lp.errors.count, "error") %> prohibited
          this lp from being saved:
        </h2>
        <ul>
          <% @lp.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="content_image">
      <% if @lp.image.exists? %>
        <%= image_tag @lp.image.url %></br>
      <% end %>
      <%= form.file_field :image %>
    </div>

    <div class="content_text">
      <p>
        <%= form.collection_select(:artist_id, Artist.all, :id, :name) %>
      </p>
      
      <p>
        <%= form.label :Name %><br>
        <%= form.text_field :name %>
      </p>

      <p>
        <%= form.label :Description %><br>
        <%= form.text_area :description %>
      </p>
    </div>

    <div class="clear"></div>
    <%= form.submit 'Update', :class => "button_update" %>
   
  <% end %>
</div>

app/views/lps/index.html.erb
<section class="menu">
  <%= link_to 'Artists', artists_path, :class => "button"  %>
  <%= link_to 'Albums', lps_path, :class => "button active" %>
</section>

<div class="center_content">
  <h1>Albums
  <%= link_to '<i class="fa fa-plus-circle"></i>'.html_safe, new_lp_path, :class => "button_new" %></h1>
   
  <table class="list">
   
    <% @lps.each do |lp| %>
      <tr>
        <td><div class="image" style="background-image: url(<%= lp.image.url %>)"></div></td>
        <td><%= lp.name %></td>
        <td><%= lp.description %></td>
        <td>
          <%= link_to '<i class="fa fa-eye"></i>'.html_safe, lp_path(lp) %>
        </td>
        <td>
          <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_lp_path(lp) %>
        </td>
        <td><%= link_to '<i class="fa fa-trash"></i>'.html_safe, lp_path(lp),
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </table>

</div>

app/views/lps/new.html.erb
<section class="menu">
	<a href="javascript:history.back()" class="button">Back</a>
  	<%= link_to 'Artists', artists_path, :class => "button"  %>
  	<%= link_to 'Albums', lps_path, :class => "button active" %>
</section>

<div class="center_content">
	<h1>New Album</h1>

	<%= form_for(:lp, :url => lps_path, :html => {:multipart => true}) do |form| %>

		<% if @lp.errors.any? %>
		    <div id="error_explanation">
		      	<h2>
			        <%= pluralize(@lp.errors.count, "error") %> prohibited
			        this lp from being saved:
		      	</h2>
		      	<ul>
			        <% @lp.errors.full_messages.each do |msg| %>
			          <li><%= msg %></li>
			        <% end %>
		      	</ul>
		    </div>
		<% end %>

		<p>
			<%= form.collection_select(:artist_id, Artist.all, :id, :name) %>
		</p>

	  	<p>
		    <%= form.label :Name %><br>
		    <%= form.text_field :name %>
	  	</p>
	 
	  	<p>
		    <%= form.label :Description %><br>
		    <%= form.text_area :description %>
	  	</p>

	  	<p>
		    <%= form.label :Image %><br>
		    <%= form.file_field :image %>
	  	</p>
	 
	  	<p>
	    	<%= form.submit 'Save' %>
	  	</p>
	<% end %>
</div>

app/views/lps/show.html.erb
<section class="menu">
 	<a href="javascript:history.back()" class="button">Back</a>
 	<%= link_to 'Artists', artists_path, :class => "button"  %>
  	<%= link_to 'Albums', lps_path, :class => "button active" %>
</section>

<div class="center_content">
	<div class="content_image">
	  <%= image_tag @lp.image.url %>
	</div>
	<div class="content_text">
		<p>
		  <strong>Artist:</strong>
		  <%= @lp.artist.name %>
		</p>
		<p>
		  <strong>Album Name:</strong>
		  <%= @lp.name %>
		</p>
		 
		<p>
		  <strong>Description:</strong>
		  <%= @lp.description %>
		</p>
	</div>
</div>

app/views/welcome/index.html.erb
<div class="welcome_content">
	<h1>Discography Project</h1>

	<%= link_to 'Artists', artists_path, :class => "button"  %>
	<%= link_to 'Albums', lps_path, :class => "button" %>
</div>